const dataTemplate = {
  "project_name" : "",
  "site_manager_first_name" : "",
  "site_manager_last_name" : "",
  "site_manager_member_id" : "",
  "site_manager_membership_role" : "",
  "alt_site_manager_first_name" : "",
  "alt_site_manager_last_name" : "",
  "alt_site_manager_member_id" : "",
  "alt_site_manager_membership_role" : "",
  "local_admin_first_name" : "",
  "local_admin_last_name" : "",
  "local_admin_member_id" : "",
  "local_admin_membership_role" : "",
  "alt_local_admin_first_name" : "",
  "alt_local_admin_last_name" : "",
  "alt_local_admin_member_id" : "",
  "alt_local_admin_membership_role" : "",
  "peer_support_first_name" : "",
  "peer_support_member_id" : "",
  "peer_support_membership_role" : "",
  "alt_peer_support_first_name" : "",
  "alt_peer_support_member_id" : "",
  "alt_peer_support_membership_role" : "",
  "project_start_date" : "",
  "project_email" : "",
  "project_phone" : "",
  "address1" : "",
  "address2" : "",
  "city" : "",
  "State" : "",
  "zipCode" : "",
  "mail_address1" : "",
  "mail_address2" : "",
  "mail_city" : "",
  "mail_state" : "",
  "mail_zipCode" : "",
  "partners": [],
  "events": [],
}

const phoenixData = {
  "_id" : ObjectId("6170b3e986fe526bf6bdcb8f"),
  "project_name" : "TriAge Phoenix",
  "site_manager_first_name" : "Easy",
  "site_manager_last_name" : "Mahaffey",
  "site_manager_member_id" : "",
  "site_manager_membership_role" : "",
  "alt_site_manager_first_name" : "",
  "alt_site_manager_last_name" : "",
  "alt_site_manager_member_id" : "",
  "alt_site_manager_membership_role" : "",
  "local_admin_first_name" : "",
  "local_admin_last_name" : "",
  "local_admin_member_id" : "",
  "local_admin_membership_role" : "",
  "alt_local_admin_first_name" : "",
  "alt_local_admin_last_name" : "",
  "alt_local_admin_member_id" : "",
  "alt_local_admin_membership_role" : "",
  "peer_support_first_name" : "Easy",
  "peer_support_member_id" : "",
  "peer_support_membership_role" : "peer_support",
  "alt_peer_support_first_name" : "",
  "alt_peer_support_member_id" : "",
  "alt_peer_support_membership_role" : "",
  "project_start_date" : ISODate("2021-10-21T14:27:17.013Z"),
  "project_email" : "triage_az_phoenix@triageproject.com",
  "project_phone" : "",
  "address1" : "",
  "address2" : "",
  "city" : "",
  "State" : "",
  "zipCode" : "",
  "mail_address1" : "",
  "mail_address2" : "",
  "mail_city" : "",
  "mail_state" : "",
  "mail_zipCode" : "",
  "partners": [],
  "events": [],
}