const mongoose = require("mongoose");

const VendorSchema = new mongoose.Schema({
  member_id: { type: String },
  organization_name: { type: String },
  password: { type: String, trim: true },
  org_branch: { type: String },
  date_organization_joined: { type: Date, default: Date.now() },
  org_email: { type: String },
  org_website: { type: String },
  org_phone: { type: String },
  org_phone_ext: { type: String },
  org_alt_phone: { type: String },
  org_cell_phone: { type: String },
  org_fax: { type: String },
  poc_first_name: { type: String },
  poc_last_name: { type: String },
  poc_title: { type: String },
  alt_poc_first_name: { type: String },
  alt_poc_last_name: { type: String },
  alt_poc_title: { type: String },
  alt_poc_phone: { type: String },
  alt_poc_email: { type: String },
  address1: { type: String },
  address2: { type: String },
  city: { type: String },
  State: { type: String },
  zipCode: { type: String },
  mail_address1: { type: String },
  mail_address2: { type: String },
  mail_city: { type: String },
  mail_State: { type: String },
  mail_zipCode: { type: String },
  eligibility: { type: String },
  custody_level: { type: String },
  adoc_approved: { type: String },
  ahcccs_approved: { type: String },
  azrha_approved: { type: String },
  info: { type: String },
  vendor_loggedIn: { type: Boolean, default: false },
  vendor_status: { type: String, default: "Active" },
  membership_role: { type: String, default: "Member" },
  membership_status: { type: String, default: "Inactive" },
  vendor_privacy: { type: String },
  vendor_text: { type: String },
  vendor_image: { type: String },
  vendor_url: { type: String },
  /// Services ///
  serviceDate: { type: Date, default: Date.now() },
  service: { type: String },
  service_type: { type: String },
  service_category: { type: String },
  tertiary_category: { type: String },
  service_source: { type: String },
  veterans_services: { type: String },
});

module.exports = mongoose.model("Vendor", VendorSchema);
